<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Euterpe.Tasks\Euterpe.Tasks.targets"/>

    <Target Name="GenerateTheme" BeforeTargets="BeforeBuild">
        <GenerateTheme AvaloniaResourceFiles="@(AvaloniaXaml)"/>
    </Target>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Labs.AnimatedImage"/>
        <PackageReference Include="Avalonia.Labs.Controls"/>
        <PackageReference Include="Irihi.Ursa"/>
        <PackageReference Include="Semi.Avalonia"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Euterpe.Abstractions\Euterpe.Abstractions.csproj"/>
        <ProjectReference Include="..\Euterpe.Models\Euterpe.Models.csproj"/>
        <ProjectReference Include="..\Euterpe.Tasks\Euterpe.Tasks.csproj"/>
    </ItemGroup>
</Project>