//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModTools.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MsgBox {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgBox() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashModTools.Localization.MsgBox.MsgBox", typeof(MsgBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MsgBox_Button_No {
            get {
                return ResourceManager.GetString("MsgBox_Button_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No and Don&apos;t Ask Again.
        /// </summary>
        public static string MsgBox_Button_NoNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_NoNoAsk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MsgBox_Button_Yes {
            get {
                return ResourceManager.GetString("MsgBox_Button_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes and Don&apos;t Ask Again.
        /// </summary>
        public static string MsgBox_Button_YesNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_YesNoAsk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your downloaded mods are broken\nPlease delete 0KB mods if they exist, then restart the application\n{0}.
        /// </summary>
        public static string MsgBox_Content_BrokenMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_BrokenMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod enable/disable failed\n{0}.
        /// </summary>
        public static string MsgBox_Content_ChangeModStateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod enable/disable failed. Is the game running?\n{0}.
        /// </summary>
        public static string MsgBox_Content_ChangeModStateFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Game", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod enable/disable failed. Unauthorized\n{0}.
        /// </summary>
        public static string MsgBox_Content_ChangeModStateFailed_Unauthorized {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Checking updates failed\nAre you online?.
        /// </summary>
        public static string MsgBox_Content_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CheckUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose correct Muse Dash folder first!.
        /// </summary>
        public static string MsgBox_Content_ChooseCorrectPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChooseCorrectPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t chosen a Muse Dash Folder\nPlease choose the folder.
        /// </summary>
        public static string MsgBox_Content_ChoosePath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChoosePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot copy Updater to target path\n{0}.
        /// </summary>
        public static string MsgBox_Content_CopyUpdaterFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CopyUpdaterFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete MelonLoader.zip in\n{0}\nError:{1}\nTry to manually delete.
        /// </summary>
        public static string MsgBox_Content_DeleteMelonLoaderZipFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_DeleteMelonLoaderZipFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is used by {1} as dependency\nAre you sure you want to delete this mod?.
        /// </summary>
        public static string MsgBox_Content_DeleteModConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_DeleteModConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is used by {1} as dependency\nAre you sure you want to disable this mod?.
        /// </summary>
        public static string MsgBox_Content_DisableModConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_DisableModConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable the mods dependent on {0}?.
        /// </summary>
        public static string MsgBox_Content_DisableReverseDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_DisableReverseDependency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgBox_Content_DotNetRuntimeNotFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_DotNetRuntimeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chart download failed\n{0}.
        /// </summary>
        public static string MsgBox_Content_DownloadChartFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_DownloadChartFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chart {0} has been successfully downloaded\n.
        /// </summary>
        public static string MsgBox_Content_DownloadChartSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_DownloadChartSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please manually choose and delete the duplicated mod\n{0}.
        /// </summary>
        public static string MsgBox_Content_DuplicateMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_DuplicateMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable {0}&apos;s dependency {1}?.
        /// </summary>
        public static string MsgBox_Content_EnableDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_EnableDependency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to verify MuseDash.exe\nMake sure you selected the right folder.
        /// </summary>
        public static string MsgBox_Content_ExeVerifyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ExeVerifyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your game path doesn&apos;t contain &quot;steamapps\common\Muse Dash\musedash.exe&quot;\nAre you using a pirated version?.
        /// </summary>
        public static string MsgBox_Content_GamePathError {
            get {
                return ResourceManager.GetString("MsgBox_Content_GamePathError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get mod list from any source.
        /// </summary>
        public static string MsgBox_Content_GetModListFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_GetModListFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have an incorrect MelonLoader version installed: {0}\nPlease use the button in the ModManage window to install MelonLoader 0.5.7.
        /// </summary>
        public static string MsgBox_Content_IncorrectMelonLoaderVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_IncorrectMelonLoaderVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MuseDash.exe is not the correct version \nAre you using a pirated or modified version?.
        /// </summary>
        public static string MsgBox_Content_IncorrectVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_IncorrectVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dependency {0} failed to install\n{1}.
        /// </summary>
        public static string MsgBox_Content_InstallDependencyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallDependencyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You did not install MelonLoader\nThis is needed to run all the mods\nInstall Now?.
        /// </summary>
        public static string MsgBox_Content_InstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MelonLoader download failed\n{0}.
        /// </summary>
        public static string MsgBox_Content_InstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MelonLoader download failed due to internet\nAre you online?\n{0}.
        /// </summary>
        public static string MsgBox_Content_InstallMelonLoaderFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed_Internet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MelonLoader has been successfully installed\n.
        /// </summary>
        public static string MsgBox_Content_InstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod installation failed\n{0}.
        /// </summary>
        public static string MsgBox_Content_InstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod installation failed. Is the game running?\n{0}.
        /// </summary>
        public static string MsgBox_Content_InstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Game", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod installation failed. Are you online?\n{0}.
        /// </summary>
        public static string MsgBox_Content_InstallModFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Internet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully installed\n.
        /// </summary>
        public static string MsgBox_Content_InstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have MuseDashModTools mod installed\nThis checks for available updates to all the mods when launching Muse Dash\nInstall Now?.
        /// </summary>
        public static string MsgBox_Content_InstallModTools {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModTools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detected Muse Dash folder path is {0}\nIs this the correct game folder?.
        /// </summary>
        public static string MsgBox_Content_InstallPathConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallPathConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path you have chosen is invalid. Try again.
        /// </summary>
        public static string MsgBox_Content_InvalidPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_InvalidPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update check successful\nYou are using the latest version of Muse Dash Mod Tools.
        /// </summary>
        public static string MsgBox_Content_LatestVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_LatestVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log analysis completed, no obvious errors are found in your log file\nIf you still have issues please go to troubleshoot channel.
        /// </summary>
        public static string MsgBox_Content_LogAnalyzeComplete {
            get {
                return ResourceManager.GetString("MsgBox_Content_LogAnalyzeComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A newer version of Muse Dash Mod Tools ({0}) is released\n\nDo you want to install it now?\n\nRelease Title:\n{1}\n\nRelease Info:\n{2}.
        /// </summary>
        public static string MsgBox_Content_NewerVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_NewerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have application path in the log.
        /// </summary>
        public static string MsgBox_Content_NoApplicationPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoApplicationPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No charts found in the folder.
        /// </summary>
        public static string MsgBox_Content_NoBmsFile {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoBmsFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find purchase record for Muse Dash&apos;s DLC\nYou have to buy it in order to play custom charts.
        /// </summary>
        public static string MsgBox_Content_NoDlcPurchased {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoDlcPurchased", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This mod does not have an available resource for download\n.
        /// </summary>
        public static string MsgBox_Content_NoDownloadLink {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoDownloadLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find MuseDash.exe and/or GameAssembly.dll\nPlease choose the right folder.
        /// </summary>
        public static string MsgBox_Content_NoExeFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoExeFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot verify that you have bought the game on Steam\nAre you using a pirated version?.
        /// </summary>
        public static string MsgBox_Content_NoInstallRecord {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoInstallRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Log File Found\nYou have to launch the game once after installing MelonLoader to generate log.
        /// </summary>
        public static string MsgBox_Content_NoLogFile {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoLogFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find MelonLoader Folder\nHave you installed MelonLoader?.
        /// </summary>
        public static string MsgBox_Content_NoMelonLoaderFolder {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoMelonLoaderFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find MelonLoader version from log.
        /// </summary>
        public static string MsgBox_Content_NoMelonLoaderVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoMelonLoaderVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your stored Muse Dash Folder path is null\nPlease choose the correct folder.
        /// </summary>
        public static string MsgBox_Content_NullPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_NullPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is outdated, please update using &quot;ModManage&quot;page.
        /// </summary>
        public static string MsgBox_Content_OutdatedMod {
            get {
                return ResourceManager.GetString("MsgBox_Content_OutdatedMod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have already downloaded the chart {0}\nContinue downloading and overriding the existing file?.
        /// </summary>
        public static string MsgBox_Content_OverrideChart {
            get {
                return ResourceManager.GetString("MsgBox_Content_OverrideChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot read current game version\nIs your Muse Dash installation complete?\nPlease check your globalgamemanagers file in\n{0}.
        /// </summary>
        public static string MsgBox_Content_ReadGameVersionFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReadGameVersionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have not registered for Headquarters\nPlease register in #bot-commands channel in MDMC discord or mdmc.moe website.
        /// </summary>
        public static string MsgBox_Content_RegisterHQ {
            get {
                return ResourceManager.GetString("MsgBox_Content_RegisterHQ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are asking to reinstall {0}\nPlease confirm your operation.
        /// </summary>
        public static string MsgBox_Content_ReinstallMod {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReinstallMod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are asking to uninstall MelonLoader\nPlease confirm your operation.
        /// </summary>
        public static string MsgBox_Content_UninstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot uninstall MelonLoader\nPlease make sure your game is not running!.
        /// </summary>
        public static string MsgBox_Content_UninstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MelonLoader has been successfully uninstalled\n.
        /// </summary>
        public static string MsgBox_Content_UninstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod uninstall failed. Is the game running?\n{0}.
        /// </summary>
        public static string MsgBox_Content_UninstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod uninstall failed\n{0}.
        /// </summary>
        public static string MsgBox_Content_UninstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Game", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot delete file that doesn&apos;t exist.
        /// </summary>
        public static string MsgBox_Content_UninstallModFailed_Null {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Null", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully deleted\n.
        /// </summary>
        public static string MsgBox_Content_UninstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot unzip MelonLoader.zip in\n{0}\nError:{1}\nTry to manually unzip?.
        /// </summary>
        public static string MsgBox_Content_UnzipMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UnzipMelonLoaderFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find Updater\nPlease make sure you have downloaded full software,\nand check your antivirus.
        /// </summary>
        public static string MsgBox_Content_UpdaterNotFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_UpdaterNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analysis successful.
        /// </summary>
        public static string MsgBox_Title_AnalyzeSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Title_AnalyzeSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string MsgBox_Title_Failure {
            get {
                return ResourceManager.GetString("MsgBox_Title_Failure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string MsgBox_Title_Notice {
            get {
                return ResourceManager.GetString("MsgBox_Title_Notice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MsgBox_Title_Success {
            get {
                return ResourceManager.GetString("MsgBox_Title_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgBox_Title_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Title_Warning", resourceCulture);
            }
        }
    }
}
