//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModTools.Localization.MsgBox {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MuseDashModTools.Localization.MsgBox.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MsgBox_Button_No {
            get {
                return ResourceManager.GetString("MsgBox_Button_No", resourceCulture);
            }
        }
        
        public static string MsgBox_Button_NoNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_NoNoAsk", resourceCulture);
            }
        }
        
        public static string MsgBox_Button_Yes {
            get {
                return ResourceManager.GetString("MsgBox_Button_Yes", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_BrokenMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_BrokenMods", resourceCulture);
            }
        }
        
        public static string MsgBox_Button_YesNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_YesNoAsk", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ChangeModStateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ChangeModStateFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Game", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ChangeModStateFailed_Unauthorized {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Unauthorized", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CheckUpdateFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ChooseCorrectPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChooseCorrectPath", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ChoosePath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChoosePath", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_CopyUpdaterFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CopyUpdaterFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DeleteMelonLoaderZipFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_DeleteMelonLoaderZipFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DeleteModConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_DeleteModConfirm", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DisableReverseDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_DisableReverseDependency", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DisableModConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_DisableModConfirm", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DuplicateMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_DuplicateMods", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_EnableDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_EnableDependency", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ExeVerifyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ExeVerifyFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_GamePathError {
            get {
                return ResourceManager.GetString("MsgBox_Content_GamePathError", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_GetModListFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_GetModListFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_IncorrectMelonLoaderVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_IncorrectMelonLoaderVersion", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_IncorrectVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_IncorrectVersion", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallDependencyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallDependencyFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoader", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallMelonLoaderFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed_Internet", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Game", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallModFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Internet", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallModTools {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModTools", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InstallPathConfirm {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallPathConfirm", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_InvalidPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_InvalidPath", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_LatestVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_LatestVersion", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_LogAnalyzeComplete {
            get {
                return ResourceManager.GetString("MsgBox_Content_LogAnalyzeComplete", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NewerVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_NewerVersion", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoApplicationPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoApplicationPath", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoDlcPurchased {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoDlcPurchased", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoDownloadLink {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoDownloadLink", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoExeFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoExeFound", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoInstallRecord {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoInstallRecord", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoLogFile {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoLogFile", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoMelonLoaderFolder {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoMelonLoaderFolder", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoMelonLoaderVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoMelonLoaderVersion", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NullPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_NullPath", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_OutdatedMod {
            get {
                return ResourceManager.GetString("MsgBox_Content_OutdatedMod", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ReadGameVersionFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReadGameVersionFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_RegisterHQ {
            get {
                return ResourceManager.GetString("MsgBox_Content_RegisterHQ", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_ReinstallMod {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReinstallMod", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoader", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Game", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallModFailed_Null {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Null", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UninstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UnzipMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UnzipMelonLoaderFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_UpdaterNotFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_UpdaterNotFound", resourceCulture);
            }
        }
        
        public static string MsgBox_Title_AnalyzeSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Title_AnalyzeSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Title_Failure {
            get {
                return ResourceManager.GetString("MsgBox_Title_Failure", resourceCulture);
            }
        }
        
        public static string MsgBox_Title_Notice {
            get {
                return ResourceManager.GetString("MsgBox_Title_Notice", resourceCulture);
            }
        }
        
        public static string MsgBox_Title_Success {
            get {
                return ResourceManager.GetString("MsgBox_Title_Success", resourceCulture);
            }
        }
        
        public static string MsgBox_Title_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Title_Warning", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DownloadChartFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_DownloadChartFailed", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DownloadChartSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_DownloadChartSuccess", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_OverrideChart {
            get {
                return ResourceManager.GetString("MsgBox_Content_OverrideChart", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_NoBmsFile {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoBmsFile", resourceCulture);
            }
        }
        
        public static string MsgBox_Content_DotNetRuntimeNotFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_DotNetRuntimeNotFound", resourceCulture);
            }
        }
    }
}
