<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAotCompatible>false</IsAotCompatible>
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="JetBrains.dotCover.Framework" />
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Mocks"/>
        <PackageReference Include="TUnit.Mocks.Http"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\build\Euterpe.Releaser\Euterpe.Releaser.csproj"/>
    </ItemGroup>

</Project>
