<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="StuDev.AotAnywhere"/>

    <Import Condition="'$(IsPublishing)' == 'true'" Project="..\..\Publish.props"/>

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <AvaloniaResource Remove="Assets\Raw\**"/>
        <Content Include="Assets\Icon.ico"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Autofac.Extensions.DependencyInjection"/>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="Avalonia.Labs.AnimatedImage"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Irihi.Ursa"/>
        <PackageReference Include="Irihi.Ursa.Themes.Semi"/>

        <PackageReference Include="ObservableCollections"/>
        <PackageReference Include="R3Extensions.Avalonia"/>
        <PackageReference Include="Semi.Avalonia"/>
        <PackageReference Include="Semver"/>
        <PackageReference Include="Velopack"/>
        <PackageReference Include="Xaml.Behaviors.Interactions.DragAndDrop"/>
    </ItemGroup>

    <!-- Avalonia Diagnostics Package-->
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Euterpe.Abstractions\Euterpe.Abstractions.csproj"/>
        <ProjectReference Include="..\Euterpe.Core\Euterpe.Core.csproj"/>
        <ProjectReference Include="..\Euterpe.CodeAnalysis\Euterpe.CodeAnalysis.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Euterpe.Controls\Euterpe.Controls.csproj"/>
    </ItemGroup>

</Project>