global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using MuseDashModTools.Generators.Extensions;
global using MuseDashModTools.Generators.StringBuilders;
global using static MuseDashModTools.Generators.BuildInfo;
global using static MuseDashModTools.Generators.SourceGenerationTexts;
global using static MuseDashModTools.Generators.SourceGeneratorHelper;