global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using JetBrains.Annotations;
global using MuseDashModTools.Abstractions;
global using MuseDashModTools.Core.Extensions;
global using MuseDashModTools.Core.Utils;
global using MuseDashModTools.Models;
global using MuseDashModTools.Models.Enums;
global using MuseDashModTools.Models.GitHub;
global using Semver;
global using Serilog;
global using Ursa.Controls;
global using static MuseDashModTools.Localization.MsgBox.Resources;
global using static MuseDashModTools.Localization.General.Resources;
global using static MuseDashModTools.Constants.BuildInfo;
global using static MuseDashModTools.Constants.GitHubConstants;