name: Bug Report
description: Tell us a bug
labels: "bug"
body:
  - type: checkboxes
    id: checking1
    attributes:
      label: I'm using the latest build release of Muse Dash Mod Tools and this problem still exists.
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: checking2
    attributes:
      label: There are no similar issues on the issue list
      description: https://github.com/MDModsDev/MuseDashModToolsUI/issues
      options:
        - label: "Yes"
          required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: which OS you are using ?
      options:
        - Windows 10 and below
        - Windows 11
        - Ubuntu
        - Other Linux distribution
    validations:
      required: true

  - type: textarea
    id: bug_detail
    attributes:
      label: Bug Detail
      placeholder: Please describe your problem in detail
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
      placeholder: |-
        Clicking on this box and drag your screenshots or videos here to upload. 
        Make sure the screenshots or videos are displayed normally after submitting the issue
    validations:
      required: false

  - type: textarea
    id: download
    attributes:
      label: Logs
      placeholder: |-
        1. Go to Logs folder under the application folder (usually MuseDashModToolsUI\Logs) and choose the bottom file.
        2. If the application crashed, it should automatically open the folder and select the log file
        3. Drag and drop the log file (*.log) here
    validations:
      required: true
