name: Help Wanted
description: You've met a problem and need help
labels: "help wanted"
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: which OS you are using ?
      options:
        - Windows 10 and below
        - Windows 11
        - Ubuntu
        - Other Linux distribution
    validations:
      required: true

  - type: textarea
    id: problem_detail
    attributes:
      label: Problem Detail (Optional)
      placeholder: Please describe your problem
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
      placeholder: |-
        Clicking on this box and drag your screenshots or videos here to upload. 
        Make sure the screenshots or videos are displayed normally after submitting the issue
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: |-
        1. Go to Logs folder under the application folder (usually MuseDashModToolsUI\Logs) and choose the bottom file.
        2. If the application crashed, it should automatically open the folder and select the log file
        3. Drag and drop the log file (*.log) here
    validations:
      required: true
