//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModToolsUI.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MuseDashModToolsUI.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string XAML_About_Project {
            get {
                return ResourceManager.GetString("XAML_About_Project", resourceCulture);
            }
        }
        
        internal static string XAML_Check_Update {
            get {
                return ResourceManager.GetString("XAML_Check_Update", resourceCulture);
            }
        }
        
        internal static string XAML_All {
            get {
                return ResourceManager.GetString("XAML_All", resourceCulture);
            }
        }
        
        internal static string XAML_Enabled {
            get {
                return ResourceManager.GetString("XAML_Enabled", resourceCulture);
            }
        }
        
        internal static string XAML_Installed {
            get {
                return ResourceManager.GetString("XAML_Installed", resourceCulture);
            }
        }
        
        internal static string XAML_Outdated {
            get {
                return ResourceManager.GetString("XAML_Outdated", resourceCulture);
            }
        }
        
        internal static string XAML_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Incompatible", resourceCulture);
            }
        }
        
        internal static string XAML_Install_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Install_MelonLoader", resourceCulture);
            }
        }
        
        internal static string XAML_Uninstall_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Uninstall_MelonLoader", resourceCulture);
            }
        }
        
        internal static string XAML_Path {
            get {
                return ResourceManager.GetString("XAML_Path", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFolder {
            get {
                return ResourceManager.GetString("XAML_ModsFolder", resourceCulture);
            }
        }
        
        internal static string XAML_SearchBar {
            get {
                return ResourceManager.GetString("XAML_SearchBar", resourceCulture);
            }
        }
        
        internal static string XAML_Uninstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Uninstall_Mod", resourceCulture);
            }
        }
        
        internal static string XAML_Install_Mod {
            get {
                return ResourceManager.GetString("XAML_Install_Mod", resourceCulture);
            }
        }
        
        internal static string XAML_Reinstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Reinstall_Mod", resourceCulture);
            }
        }
        
        internal static string XAML_Update_Mod {
            get {
                return ResourceManager.GetString("XAML_Update_Mod", resourceCulture);
            }
        }
        
        internal static string MsgBox_Title_Failure {
            get {
                return ResourceManager.GetString("MsgBox_Title_Failure", resourceCulture);
            }
        }
        
        internal static string MsgBox_Title_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Title_Warning", resourceCulture);
            }
        }
        
        internal static string MsgBox_Title_Success {
            get {
                return ResourceManager.GetString("MsgBox_Title_Success", resourceCulture);
            }
        }
        
        internal static string MsgBox_Button_Yes {
            get {
                return ResourceManager.GetString("MsgBox_Button_Yes", resourceCulture);
            }
        }
        
        internal static string MsgBox_Button_No {
            get {
                return ResourceManager.GetString("MsgBox_Button_No", resourceCulture);
            }
        }
        
        internal static string MsgBox_Button_YesNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_YesNoAsk", resourceCulture);
            }
        }
        
        internal static string MsgBox_Button_NoNoAsk {
            get {
                return ResourceManager.GetString("MsgBox_Button_NoNoAsk", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_LatestVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_LatestVersion", resourceCulture);
            }
        }
        
        internal static string MsgBox_Title_Notice {
            get {
                return ResourceManager.GetString("MsgBox_Title_Notice", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_NewerVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_NewerVersion", resourceCulture);
            }
        }
        
        internal static string FolderDialog_Title {
            get {
                return ResourceManager.GetString("FolderDialog_Title", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InvalidPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_InvalidPath", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_NullPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_NullPath", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ChoosePath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChoosePath", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_BrokenMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_BrokenMods", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CheckUpdateFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UpdaterNotFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_UpdaterNotFound", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_CopyUpdaterFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_CopyUpdaterFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_NoExeFound {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoExeFound", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_IncorrectVersion {
            get {
                return ResourceManager.GetString("MsgBox_Content_IncorrectVersion", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ExeVerifyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ExeVerifyFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ReadGameVersionFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReadGameVersionFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoader", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderSuccess", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoaderFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_NoMelonLoaderFolder {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoMelonLoaderFolder", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ChooseCorrectPath {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChooseCorrectPath", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallModTools {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModTools", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_NoDownloadLink {
            get {
                return ResourceManager.GetString("MsgBox_Content_NoDownloadLink", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallModFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Internet", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed_Game", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallDependencyFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallDependencyFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_EnableDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_EnableDependency", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallModSuccess", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ReinstallMod {
            get {
                return ResourceManager.GetString("MsgBox_Content_ReinstallMod", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallModFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Game", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallModFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Mod_Incompatible", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Outdated {
            get {
                return ResourceManager.GetString("XAML_Mod_Outdated", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Newer {
            get {
                return ResourceManager.GetString("XAML_Mod_Newer", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Modified {
            get {
                return ResourceManager.GetString("XAML_Mod_Modified", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Normal {
            get {
                return ResourceManager.GetString("XAML_Mod_Normal", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Description {
            get {
                return ResourceManager.GetString("XAML_Mod_Description", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_CompatibleGameVersion {
            get {
                return ResourceManager.GetString("XAML_Mod_CompatibleGameVersion", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Mod_Dependencies", resourceCulture);
            }
        }
        
        internal static string XAML_Mod_Duplicate {
            get {
                return ResourceManager.GetString("XAML_Mod_Duplicate", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_EnableReverseDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_EnableReverseDependency", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_DisableDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_DisableDependency", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_DuplicateMods {
            get {
                return ResourceManager.GetString("MsgBox_Content_DuplicateMods", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallModFailed_Null {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModFailed_Null", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallModSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallModSuccess", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallDependency {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallDependency", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ChangeModStateFailed_Unauthorized {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Unauthorized", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ChangeModStateFailed_Game {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed_Game", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_ChangeModStateFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_ChangeModStateFailed", resourceCulture);
            }
        }
        
        internal static string XAML_HomePage {
            get {
                return ResourceManager.GetString("XAML_HomePage", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallMelonLoaderFailed_Internet {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed_Internet", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UnzipMelonLoaderFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_UnzipMelonLoaderFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_DeleteMelonLoaderZipFailed {
            get {
                return ResourceManager.GetString("MsgBox_Content_DeleteMelonLoaderZipFailed", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_InstallMelonLoaderSuccess {
            get {
                return ResourceManager.GetString("MsgBox_Content_InstallMelonLoaderSuccess", resourceCulture);
            }
        }
        
        internal static string MsgBox_Content_UninstallMelonLoader {
            get {
                return ResourceManager.GetString("MsgBox_Content_UninstallMelonLoader", resourceCulture);
            }
        }
        
        internal static string XAML_Tab_ModManage {
            get {
                return ResourceManager.GetString("XAML_Tab_ModManage", resourceCulture);
            }
        }
        
        internal static string XAML_Tab_Setting {
            get {
                return ResourceManager.GetString("XAML_Tab_Setting", resourceCulture);
            }
        }
    }
}
