//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModToolsUI.Localization.XAML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_XAML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_XAML() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashModToolsUI.Localization.XAML.Resources_XAML", typeof(Resources_XAML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string XAML_All {
            get {
                return ResourceManager.GetString("XAML_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Log.
        /// </summary>
        internal static string XAML_Analyze {
            get {
                return ResourceManager.GetString("XAML_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string XAML_Apply {
            get {
                return ResourceManager.GetString("XAML_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Ask.
        /// </summary>
        internal static string XAML_AskType_Always {
            get {
                return ResourceManager.GetString("XAML_AskType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string XAML_AskType_No {
            get {
                return ResourceManager.GetString("XAML_AskType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string XAML_AskType_Yes {
            get {
                return ResourceManager.GetString("XAML_AskType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Path.
        /// </summary>
        internal static string XAML_ChangePath {
            get {
                return ResourceManager.GetString("XAML_ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads: .
        /// </summary>
        internal static string XAML_Chart_Downloads {
            get {
                return ResourceManager.GetString("XAML_Chart_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes: .
        /// </summary>
        internal static string XAML_Chart_Likes {
            get {
                return ResourceManager.GetString("XAML_Chart_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Charts (Name, Author, Charter).
        /// </summary>
        internal static string XAML_Chart_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Chart_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charter: .
        /// </summary>
        internal static string XAML_Charter {
            get {
                return ResourceManager.GetString("XAML_Charter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string XAML_ChartFilterType_Easy {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string XAML_ChartFilterType_Hard {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string XAML_ChartFilterType_Hidden {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string XAML_ChartFilterType_Master {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        internal static string XAML_ChartFilterTypes {
            get {
                return ResourceManager.GetString("XAML_ChartFilterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string XAML_ChartSortOption_Default {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string XAML_ChartSortOption_Downloads {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string XAML_ChartSortOption_Latest {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string XAML_ChartSortOption_Level {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        internal static string XAML_ChartSortOption_Likes {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string XAML_ChartSortOption_Name {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: .
        /// </summary>
        internal static string XAML_ChartSortOptions {
            get {
                return ResourceManager.GetString("XAML_ChartSortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        internal static string XAML_Check_Update {
            get {
                return ResourceManager.GetString("XAML_Check_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Custom_Albums Folder.
        /// </summary>
        internal static string XAML_CustomAlbumsFolder {
            get {
                return ResourceManager.GetString("XAML_CustomAlbumsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link must end in &quot;/&quot;, and must be accessible and parsable when appending &quot;ModLinks.json&quot; to the end of the address (The same structure as the Github repository)\nTakes effect after restarting app.
        /// </summary>
        internal static string XAML_CustomDownloadSourceFormat {
            get {
                return ResourceManager.GetString("XAML_CustomDownloadSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string XAML_Download_Chart {
            get {
                return ResourceManager.GetString("XAML_Download_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Prerelease: .
        /// </summary>
        internal static string XAML_DownloadPrerelease {
            get {
                return ResourceManager.GetString("XAML_DownloadPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Source: .
        /// </summary>
        internal static string XAML_DownloadSource {
            get {
                return ResourceManager.GetString("XAML_DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string XAML_DownloadSource_Custom {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitee.
        /// </summary>
        internal static string XAML_DownloadSource_Gitee {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Gitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        internal static string XAML_DownloadSource_Github {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Mirror.
        /// </summary>
        internal static string XAML_DownloadSource_GithubMirror {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_GithubMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string XAML_Enabled {
            get {
                return ResourceManager.GetString("XAML_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        internal static string XAML_Font {
            get {
                return ResourceManager.GetString("XAML_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate.
        /// </summary>
        internal static string XAML_HelpTranslate {
            get {
                return ResourceManager.GetString("XAML_HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        internal static string XAML_HomePage {
            get {
                return ResourceManager.GetString("XAML_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible.
        /// </summary>
        internal static string XAML_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install\nMelonLoader.
        /// </summary>
        internal static string XAML_Install_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Install_MelonLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string XAML_Install_Mod {
            get {
                return ResourceManager.GetString("XAML_Install_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string XAML_Installed {
            get {
                return ResourceManager.GetString("XAML_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string XAML_Language {
            get {
                return ResourceManager.GetString("XAML_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        internal static string XAML_LogFolder {
            get {
                return ResourceManager.GetString("XAML_LogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string XAML_Mod_CompatibleGameVersion {
            get {
                return ResourceManager.GetString("XAML_Mod_CompatibleGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies: .
        /// </summary>
        internal static string XAML_Mod_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Mod_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} \n\nAuthor: {1} \nOnline Version: {2}\nCompatible Game Version: {3}.
        /// </summary>
        internal static string XAML_Mod_Description {
            get {
                return ResourceManager.GetString("XAML_Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated by: .
        /// </summary>
        internal static string XAML_Mod_Duplicate {
            get {
                return ResourceManager.GetString("XAML_Mod_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s {1} version is incompatible with your game version.
        /// </summary>
        internal static string XAML_Mod_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Mod_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (Modified).
        /// </summary>
        internal static string XAML_Mod_Modified {
            get {
                return ResourceManager.GetString("XAML_Mod_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (WOW MOD DEV).
        /// </summary>
        internal static string XAML_Mod_Newer {
            get {
                return ResourceManager.GetString("XAML_Mod_Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0}.
        /// </summary>
        internal static string XAML_Mod_Normal {
            get {
                return ResourceManager.GetString("XAML_Mod_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (Has a newer version: {1}).
        /// </summary>
        internal static string XAML_Mod_Outdated {
            get {
                return ResourceManager.GetString("XAML_Mod_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mods    (Name, Author, Descriptions).
        /// </summary>
        internal static string XAML_Mod_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Mod_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string XAML_ModsFolder {
            get {
                return ResourceManager.GetString("XAML_ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        internal static string XAML_Outdated {
            get {
                return ResourceManager.GetString("XAML_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muse Dash Folder Path.
        /// </summary>
        internal static string XAML_Path {
            get {
                return ResourceManager.GetString("XAML_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        internal static string XAML_Reinstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Reinstall_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        internal static string XAML_ReportBug {
            get {
                return ResourceManager.GetString("XAML_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mods    (Name, Author, Descriptions).
        /// </summary>
        internal static string XAML_SearchBar {
            get {
                return ResourceManager.GetString("XAML_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable dependents when deleting Mod.
        /// </summary>
        internal static string XAML_Setting_DisableDependency_Delete {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable dependents when disabling Mod.
        /// </summary>
        internal static string XAML_Setting_DisableDependency_Disable {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dependencies when enabling Mod.
        /// </summary>
        internal static string XAML_Setting_EnableDependency_Enable {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dependencies when installing Mod.
        /// </summary>
        internal static string XAML_Setting_EnableDependency_Install {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string XAML_Tab_About {
            get {
                return ResourceManager.GetString("XAML_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string XAML_Tab_ChartDownload {
            get {
                return ResourceManager.GetString("XAML_Tab_ChartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string XAML_Tab_LogAnalysis {
            get {
                return ResourceManager.GetString("XAML_Tab_LogAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string XAML_Tab_ModManage {
            get {
                return ResourceManager.GetString("XAML_Tab_ModManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string XAML_Tab_Setting {
            get {
                return ResourceManager.GetString("XAML_Tab_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string XAML_TroubleShoot {
            get {
                return ResourceManager.GetString("XAML_TroubleShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall\nMelonLoader.
        /// </summary>
        internal static string XAML_Uninstall_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Uninstall_MelonLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string XAML_Uninstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Uninstall_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string XAML_Update_Mod {
            get {
                return ResourceManager.GetString("XAML_Update_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the link of custom download source.
        /// </summary>
        internal static string XAML_UseCustomDownloadSource {
            get {
                return ResourceManager.GetString("XAML_UseCustomDownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData.
        /// </summary>
        internal static string XAML_UserDataFolder {
            get {
                return ResourceManager.GetString("XAML_UserDataFolder", resourceCulture);
            }
        }
    }
}
