//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModTools.Localization.ModDescription {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MuseDashModTools.Localization.ModDescription.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Accuracy_Indicator {
            get {
                return ResourceManager.GetString("Accuracy Indicator", resourceCulture);
            }
        }

        public static string AccuracyDisplay {
            get {
                return ResourceManager.GetString("AccuracyDisplay", resourceCulture);
            }
        }

        public static string Alt_Tab_Mute {
            get {
                return ResourceManager.GetString("Alt Tab Mute", resourceCulture);
            }
        }

        public static string AlwaysAprilFool {
            get {
                return ResourceManager.GetString("AlwaysAprilFool", resourceCulture);
            }
        }

        public static string AlwaysBadApple {
            get {
                return ResourceManager.GetString("AlwaysBadApple", resourceCulture);
            }
        }

        public static string AlwaysPigeons {
            get {
                return ResourceManager.GetString("AlwaysPigeons", resourceCulture);
            }
        }

        public static string BestCombinationSuggest {
            get {
                return ResourceManager.GetString("BestCombinationSuggest", resourceCulture);
            }
        }

        public static string BPMDisplay {
            get {
                return ResourceManager.GetString("BPMDisplay", resourceCulture);
            }
        }

        public static string CharacterRandomizer {
            get {
                return ResourceManager.GetString("CharacterRandomizer", resourceCulture);
            }
        }

        public static string CharacterScoreboard {
            get {
                return ResourceManager.GetString("CharacterScoreboard", resourceCulture);
            }
        }

        public static string ChartDeleter {
            get {
                return ResourceManager.GetString("ChartDeleter", resourceCulture);
            }
        }

        public static string ChartReview {
            get {
                return ResourceManager.GetString("ChartReview", resourceCulture);
            }
        }

        public static string ChineseMode {
            get {
                return ResourceManager.GetString("ChineseMode", resourceCulture);
            }
        }

        public static string Cinema {
            get {
                return ResourceManager.GetString("Cinema", resourceCulture);
            }
        }

        public static string CustomAlbums {
            get {
                return ResourceManager.GetString("CustomAlbums", resourceCulture);
            }
        }

        public static string CustomAnchorSupport {
            get {
                return ResourceManager.GetString("CustomAnchorSupport", resourceCulture);
            }
        }

        public static string CustomBGBrightness {
            get {
                return ResourceManager.GetString("CustomBGBrightness", resourceCulture);
            }
        }

        public static string CustomHitSound {
            get {
                return ResourceManager.GetString("CustomHitSound", resourceCulture);
            }
        }

        public static string CustomLoadingScreens {
            get {
                return ResourceManager.GetString("CustomLoadingScreens", resourceCulture);
            }
        }

        public static string CustomResolution {
            get {
                return ResourceManager.GetString("CustomResolution", resourceCulture);
            }
        }

        public static string EffectDisable {
            get {
                return ResourceManager.GetString("EffectDisable", resourceCulture);
            }
        }

        public static string FavGirl {
            get {
                return ResourceManager.GetString("FavGirl", resourceCulture);
            }
        }

        public static string FC_AP_indicator {
            get {
                return ResourceManager.GetString("FC AP indicator", resourceCulture);
            }
        }

        public static string FeverEffectDisable {
            get {
                return ResourceManager.GetString("FeverEffectDisable", resourceCulture);
            }
        }

        public static string Headquarters {
            get {
                return ResourceManager.GetString("Headquarters", resourceCulture);
            }
        }

        public static string HiddenQoL {
            get {
                return ResourceManager.GetString("HiddenQoL", resourceCulture);
            }
        }

        public static string IntroSkip {
            get {
                return ResourceManager.GetString("IntroSkip", resourceCulture);
            }
        }

        public static string KeybindManager {
            get {
                return ResourceManager.GetString("KeybindManager", resourceCulture);
            }
        }

        public static string LocalizeLib {
            get {
                return ResourceManager.GetString("LocalizeLib", resourceCulture);
            }
        }

        public static string MDRPC {
            get {
                return ResourceManager.GetString("MDRPC", resourceCulture);
            }
        }

        public static string ModManager {
            get {
                return ResourceManager.GetString("ModManager", resourceCulture);
            }
        }

        public static string Muse_Dash_Mirror {
            get {
                return ResourceManager.GetString("Muse Dash Mirror", resourceCulture);
            }
        }

        public static string MuseDashModTools {
            get {
                return ResourceManager.GetString("MuseDashModTools", resourceCulture);
            }
        }

        public static string NoAutoPause {
            get {
                return ResourceManager.GetString("NoAutoPause", resourceCulture);
            }
        }

        public static string NoLevelUpAnimations {
            get {
                return ResourceManager.GetString("NoLevelUpAnimations", resourceCulture);
            }
        }

        public static string PerfectDisable {
            get {
                return ResourceManager.GetString("PerfectDisable", resourceCulture);
            }
        }

        public static string PopupLib {
            get {
                return ResourceManager.GetString("PopupLib", resourceCulture);
            }
        }

        public static string PreventLowAcc {
            get {
                return ResourceManager.GetString("PreventLowAcc", resourceCulture);
            }
        }

        public static string QuickRestart {
            get {
                return ResourceManager.GetString("QuickRestart", resourceCulture);
            }
        }

        public static string QuickSwitchCombination {
            get {
                return ResourceManager.GetString("QuickSwitchCombination", resourceCulture);
            }
        }

        public static string SceneEggs {
            get {
                return ResourceManager.GetString("SceneEggs", resourceCulture);
            }
        }

        public static string Scoreboard_characters_and_elfins {
            get {
                return ResourceManager.GetString("Scoreboard characters and elfins", resourceCulture);
            }
        }

        public static string ScrollSpeed {
            get {
                return ResourceManager.GetString("ScrollSpeed", resourceCulture);
            }
        }

        public static string SearchPlusPlus {
            get {
                return ResourceManager.GetString("SearchPlusPlus", resourceCulture);
            }
        }

        public static string Song_Desc {
            get {
                return ResourceManager.GetString("Song Desc", resourceCulture);
            }
        }

        public static string Search___Folder_Tag {
            get {
                return ResourceManager.GetString("Search++ Folder Tag", resourceCulture);
            }
        }

        public static string StricterJudge {
            get {
                return ResourceManager.GetString("StricterJudge", resourceCulture);
            }
        }

        public static string True_rank_for_999_ {
            get {
                return ResourceManager.GetString("True rank for 999+", resourceCulture);
            }
        }

        public static string UI_Disable {
            get {
                return ResourceManager.GetString("UI Disable", resourceCulture);
            }
        }

        public static string UltraInstinctSleepwalking {
            get {
                return ResourceManager.GetString("UltraInstinctSleepwalking", resourceCulture);
            }
        }

        public static string UnlockAll2 {
            get {
                return ResourceManager.GetString("UnlockAll2", resourceCulture);
            }
        }

        public static string VictoryScreenSwitcher {
            get {
                return ResourceManager.GetString("VictoryScreenSwitcher", resourceCulture);
            }
        }
    }
}
