//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModTools.Localization.XAML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashModTools.Localization.XAML.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Log.
        /// </summary>
        public static string XAML_Analyze {
            get {
                return ResourceManager.GetString("XAML_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string XAML_Apply {
            get {
                return ResourceManager.GetString("XAML_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Ask.
        /// </summary>
        public static string XAML_AskType_Always {
            get {
                return ResourceManager.GetString("XAML_AskType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string XAML_AskType_No {
            get {
                return ResourceManager.GetString("XAML_AskType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string XAML_AskType_Yes {
            get {
                return ResourceManager.GetString("XAML_AskType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string XAML_Back {
            get {
                return ResourceManager.GetString("XAML_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Path.
        /// </summary>
        public static string XAML_ChangePath {
            get {
                return ResourceManager.GetString("XAML_ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads: .
        /// </summary>
        public static string XAML_Chart_Downloads {
            get {
                return ResourceManager.GetString("XAML_Chart_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes: .
        /// </summary>
        public static string XAML_Chart_Likes {
            get {
                return ResourceManager.GetString("XAML_Chart_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Charts (Name, Author, Charter).
        /// </summary>
        public static string XAML_Chart_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Chart_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charter: .
        /// </summary>
        public static string XAML_Charter {
            get {
                return ResourceManager.GetString("XAML_Charter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string XAML_ChartFilterType_Easy {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string XAML_ChartFilterType_Hard {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string XAML_ChartFilterType_Hidden {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string XAML_ChartFilterType_Master {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string XAML_ChartFilterTypes {
            get {
                return ResourceManager.GetString("XAML_ChartFilterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string XAML_ChartSortOption_Default {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string XAML_ChartSortOption_Downloads {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string XAML_ChartSortOption_Latest {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string XAML_ChartSortOption_Level {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string XAML_ChartSortOption_Likes {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string XAML_ChartSortOption_Name {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: .
        /// </summary>
        public static string XAML_ChartSortOptions {
            get {
                return ResourceManager.GetString("XAML_ChartSortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string XAML_Check_Update {
            get {
                return ResourceManager.GetString("XAML_Check_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Chart Folder.
        /// </summary>
        public static string XAML_ChooseChartPath {
            get {
                return ResourceManager.GetString("XAML_ChooseChartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config File.
        /// </summary>
        public static string XAML_ConfigFile {
            get {
                return ResourceManager.GetString("XAML_ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Custom_Albums Folder.
        /// </summary>
        public static string XAML_CustomAlbumsFolder {
            get {
                return ResourceManager.GetString("XAML_CustomAlbumsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link must end in &quot;/&quot;, and must be accessible and parsable when appending &quot;ModLinks.json&quot; to the end of the address (The same structure as the Github repository)\nTakes effect after restarting app.
        /// </summary>
        public static string XAML_CustomDownloadSourceFormat {
            get {
                return ResourceManager.GetString("XAML_CustomDownloadSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string XAML_Download_Chart {
            get {
                return ResourceManager.GetString("XAML_Download_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Prerelease: .
        /// </summary>
        public static string XAML_DownloadPrerelease {
            get {
                return ResourceManager.GetString("XAML_DownloadPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Source: .
        /// </summary>
        public static string XAML_DownloadSource {
            get {
                return ResourceManager.GetString("XAML_DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string XAML_DownloadSource_Custom {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitee.
        /// </summary>
        public static string XAML_DownloadSource_Gitee {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Gitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string XAML_DownloadSource_Github {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Mirror.
        /// </summary>
        public static string XAML_DownloadSource_GithubMirror {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_GithubMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string XAML_Font {
            get {
                return ResourceManager.GetString("XAML_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate.
        /// </summary>
        public static string XAML_HelpTranslate {
            get {
                return ResourceManager.GetString("XAML_HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        public static string XAML_HomePage {
            get {
                return ResourceManager.GetString("XAML_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string XAML_InfoJson_Author {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string XAML_InfoJson_BPM {
            get {
                return ResourceManager.GetString("XAML_InfoJson_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string XAML_InfoJson_ChartName {
            get {
                return ResourceManager.GetString("XAML_InfoJson_ChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string XAML_InfoJson_Difficulty {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Bms Difficulty.
        /// </summary>
        public static string XAML_InfoJson_HideBmsDifficulty {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Bms Message.
        /// </summary>
        public static string XAML_InfoJson_HideBmsMessage {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Bms Mode.
        /// </summary>
        public static string XAML_InfoJson_HideBmsMode {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Designer.
        /// </summary>
        public static string XAML_InfoJson_LevelDesigner {
            get {
                return ResourceManager.GetString("XAML_InfoJson_LevelDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string XAML_InfoJson_Scene {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tags.
        /// </summary>
        public static string XAML_InfoJson_SearchTags {
            get {
                return ResourceManager.GetString("XAML_InfoJson_SearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install\nMelonLoader.
        /// </summary>
        public static string XAML_Install_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Install_MelonLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string XAML_Install_Mod {
            get {
                return ResourceManager.GetString("XAML_Install_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string XAML_Language {
            get {
                return ResourceManager.GetString("XAML_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Modded.
        /// </summary>
        public static string XAML_LaunchModded {
            get {
                return ResourceManager.GetString("XAML_LaunchModded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Vanilla.
        /// </summary>
        public static string XAML_LaunchVanilla {
            get {
                return ResourceManager.GetString("XAML_LaunchVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string XAML_LogFolder {
            get {
                return ResourceManager.GetString("XAML_LogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string XAML_Mod_CompatibleGameVersion {
            get {
                return ResourceManager.GetString("XAML_Mod_CompatibleGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies: .
        /// </summary>
        public static string XAML_Mod_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Mod_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} \n\nAuthor: {1} \nOnline Version: {2}\nCompatible Game Version: {3}.
        /// </summary>
        public static string XAML_Mod_Description {
            get {
                return ResourceManager.GetString("XAML_Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated by: .
        /// </summary>
        public static string XAML_Mod_Duplicate {
            get {
                return ResourceManager.GetString("XAML_Mod_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s {1} version is incompatible with your game version.
        /// </summary>
        public static string XAML_Mod_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Mod_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (Modified).
        /// </summary>
        public static string XAML_Mod_Modified {
            get {
                return ResourceManager.GetString("XAML_Mod_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (WOW MOD DEV).
        /// </summary>
        public static string XAML_Mod_Newer {
            get {
                return ResourceManager.GetString("XAML_Mod_Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0}.
        /// </summary>
        public static string XAML_Mod_Normal {
            get {
                return ResourceManager.GetString("XAML_Mod_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Version: {0} (Has a newer version: {1}).
        /// </summary>
        public static string XAML_Mod_Outdated {
            get {
                return ResourceManager.GetString("XAML_Mod_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mods    (Name, Author, Descriptions).
        /// </summary>
        public static string XAML_Mod_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Mod_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string XAML_ModFilterType_All {
            get {
                return ResourceManager.GetString("XAML_ModFilterType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string XAML_ModFilterType_Enabled {
            get {
                return ResourceManager.GetString("XAML_ModFilterType_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible.
        /// </summary>
        public static string XAML_ModFilterType_Incompatible {
            get {
                return ResourceManager.GetString("XAML_ModFilterType_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string XAML_ModFilterType_Installed {
            get {
                return ResourceManager.GetString("XAML_ModFilterType_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        public static string XAML_ModFilterType_Outdated {
            get {
                return ResourceManager.GetString("XAML_ModFilterType_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string XAML_ModsFolder {
            get {
                return ResourceManager.GetString("XAML_ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string XAML_News {
            get {
                return ResourceManager.GetString("XAML_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string XAML_Page_About {
            get {
                return ResourceManager.GetString("XAML_Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charting.
        /// </summary>
        public static string XAML_Page_Charting {
            get {
                return ResourceManager.GetString("XAML_Page_Charting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Manage.
        /// </summary>
        public static string XAML_Page_ChartManage {
            get {
                return ResourceManager.GetString("XAML_Page_ChartManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Toolkit.
        /// </summary>
        public static string XAML_Page_ChartToolkit {
            get {
                return ResourceManager.GetString("XAML_Page_ChartToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string XAML_Page_Home {
            get {
                return ResourceManager.GetString("XAML_Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Analysis.
        /// </summary>
        public static string XAML_Page_LogAnalysis {
            get {
                return ResourceManager.GetString("XAML_Page_LogAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Develop.
        /// </summary>
        public static string XAML_Page_ModDevelop {
            get {
                return ResourceManager.GetString("XAML_Page_ModDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modding.
        /// </summary>
        public static string XAML_Page_Modding {
            get {
                return ResourceManager.GetString("XAML_Page_Modding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manage.
        /// </summary>
        public static string XAML_Page_ModManage {
            get {
                return ResourceManager.GetString("XAML_Page_ModManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string XAML_Page_Setting {
            get {
                return ResourceManager.GetString("XAML_Page_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muse Dash Folder Path.
        /// </summary>
        public static string XAML_Path {
            get {
                return ResourceManager.GetString("XAML_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string XAML_Reinstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Reinstall_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string XAML_ReportBug {
            get {
                return ResourceManager.GetString("XAML_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candyland.
        /// </summary>
        public static string XAML_Scene_Candyland {
            get {
                return ResourceManager.GetString("XAML_Scene_Candyland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle.
        /// </summary>
        public static string XAML_Scene_Castle {
            get {
                return ResourceManager.GetString("XAML_Scene_Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJMAX.
        /// </summary>
        public static string XAML_Scene_DJMAX {
            get {
                return ResourceManager.GetString("XAML_Scene_DJMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Groove.
        /// </summary>
        public static string XAML_Scene_LetsGroove {
            get {
                return ResourceManager.GetString("XAML_Scene_LetsGroove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oriental.
        /// </summary>
        public static string XAML_Scene_Oriental {
            get {
                return ResourceManager.GetString("XAML_Scene_Oriental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RainyNight.
        /// </summary>
        public static string XAML_Scene_RainyNight {
            get {
                return ResourceManager.GetString("XAML_Scene_RainyNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrocity.
        /// </summary>
        public static string XAML_Scene_Retrocity {
            get {
                return ResourceManager.GetString("XAML_Scene_Retrocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Station.
        /// </summary>
        public static string XAML_Scene_SpaceStation {
            get {
                return ResourceManager.GetString("XAML_Scene_SpaceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou.
        /// </summary>
        public static string XAML_Scene_Touhou {
            get {
                return ResourceManager.GetString("XAML_Scene_Touhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mods    (Name, Author, Descriptions).
        /// </summary>
        public static string XAML_SearchBar {
            get {
                return ResourceManager.GetString("XAML_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable dependents when deleting Mod.
        /// </summary>
        public static string XAML_Setting_DisableDependency_Delete {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable dependents when disabling Mod.
        /// </summary>
        public static string XAML_Setting_DisableDependency_Disable {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dependencies when enabling Mod.
        /// </summary>
        public static string XAML_Setting_EnableDependency_Enable {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dependencies when installing Mod.
        /// </summary>
        public static string XAML_Setting_EnableDependency_Install {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        public static string XAML_TroubleShoot {
            get {
                return ResourceManager.GetString("XAML_TroubleShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall\nMelonLoader.
        /// </summary>
        public static string XAML_Uninstall_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Uninstall_MelonLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string XAML_Uninstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Uninstall_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string XAML_Update_Mod {
            get {
                return ResourceManager.GetString("XAML_Update_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github API.
        /// </summary>
        public static string XAML_UpdateSources_GithubAPI {
            get {
                return ResourceManager.GetString("XAML_UpdateSources_GithubAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github RSS.
        /// </summary>
        public static string XAML_UpdateSources_GithubRSS {
            get {
                return ResourceManager.GetString("XAML_UpdateSources_GithubRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the link of custom download source.
        /// </summary>
        public static string XAML_UseCustomDownloadSource {
            get {
                return ResourceManager.GetString("XAML_UseCustomDownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData.
        /// </summary>
        public static string XAML_UserDataFolder {
            get {
                return ResourceManager.GetString("XAML_UserDataFolder", resourceCulture);
            }
        }
    }
}
