//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashModTools.Localization.XAML {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MuseDashModTools.Localization.XAML.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string XAML_UserDataFolder {
            get {
                return ResourceManager.GetString("XAML_UserDataFolder", resourceCulture);
            }
        }
        
        public static string XAML_ReportBug {
            get {
                return ResourceManager.GetString("XAML_ReportBug", resourceCulture);
            }
        }
        
        public static string XAML_Check_Update {
            get {
                return ResourceManager.GetString("XAML_Check_Update", resourceCulture);
            }
        }
        
        public static string XAML_DownloadSource_GithubMirror {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_GithubMirror", resourceCulture);
            }
        }
        
        public static string XAML_Analyze {
            get {
                return ResourceManager.GetString("XAML_Analyze", resourceCulture);
            }
        }
        
        public static string XAML_Apply {
            get {
                return ResourceManager.GetString("XAML_Apply", resourceCulture);
            }
        }
        
        public static string XAML_AskType_Always {
            get {
                return ResourceManager.GetString("XAML_AskType_Always", resourceCulture);
            }
        }
        
        public static string XAML_AskType_No {
            get {
                return ResourceManager.GetString("XAML_AskType_No", resourceCulture);
            }
        }
        
        public static string XAML_AskType_Yes {
            get {
                return ResourceManager.GetString("XAML_AskType_Yes", resourceCulture);
            }
        }
        
        public static string XAML_ChangePath {
            get {
                return ResourceManager.GetString("XAML_ChangePath", resourceCulture);
            }
        }
        
        public static string XAML_DownloadPrerelease {
            get {
                return ResourceManager.GetString("XAML_DownloadPrerelease", resourceCulture);
            }
        }
        
        public static string XAML_DownloadSource_Gitee {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Gitee", resourceCulture);
            }
        }
        
        public static string XAML_DownloadSource_Github {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Github", resourceCulture);
            }
        }
        
        public static string XAML_DownloadSource {
            get {
                return ResourceManager.GetString("XAML_DownloadSource", resourceCulture);
            }
        }
        
        public static string XAML_All {
            get {
                return ResourceManager.GetString("XAML_All", resourceCulture);
            }
        }
        
        public static string XAML_Enabled {
            get {
                return ResourceManager.GetString("XAML_Enabled", resourceCulture);
            }
        }
        
        public static string XAML_Font {
            get {
                return ResourceManager.GetString("XAML_Font", resourceCulture);
            }
        }
        
        public static string XAML_HelpTranslate {
            get {
                return ResourceManager.GetString("XAML_HelpTranslate", resourceCulture);
            }
        }
        
        public static string XAML_HomePage {
            get {
                return ResourceManager.GetString("XAML_HomePage", resourceCulture);
            }
        }
        
        public static string XAML_Installed {
            get {
                return ResourceManager.GetString("XAML_Installed", resourceCulture);
            }
        }
        
        public static string XAML_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Incompatible", resourceCulture);
            }
        }
        
        public static string XAML_Install_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Install_MelonLoader", resourceCulture);
            }
        }
        
        public static string XAML_Install_Mod {
            get {
                return ResourceManager.GetString("XAML_Install_Mod", resourceCulture);
            }
        }
        
        public static string XAML_Language {
            get {
                return ResourceManager.GetString("XAML_Language", resourceCulture);
            }
        }
        
        public static string XAML_LogFolder {
            get {
                return ResourceManager.GetString("XAML_LogFolder", resourceCulture);
            }
        }
        
        public static string XAML_ModsFolder {
            get {
                return ResourceManager.GetString("XAML_ModsFolder", resourceCulture);
            }
        }
        
        public static string XAML_Mod_CompatibleGameVersion {
            get {
                return ResourceManager.GetString("XAML_Mod_CompatibleGameVersion", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Mod_Dependencies", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Description {
            get {
                return ResourceManager.GetString("XAML_Mod_Description", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Duplicate {
            get {
                return ResourceManager.GetString("XAML_Mod_Duplicate", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Incompatible {
            get {
                return ResourceManager.GetString("XAML_Mod_Incompatible", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Modified {
            get {
                return ResourceManager.GetString("XAML_Mod_Modified", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Newer {
            get {
                return ResourceManager.GetString("XAML_Mod_Newer", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Normal {
            get {
                return ResourceManager.GetString("XAML_Mod_Normal", resourceCulture);
            }
        }
        
        public static string XAML_Mod_Outdated {
            get {
                return ResourceManager.GetString("XAML_Mod_Outdated", resourceCulture);
            }
        }
        
        public static string XAML_Outdated {
            get {
                return ResourceManager.GetString("XAML_Outdated", resourceCulture);
            }
        }
        
        public static string XAML_Path {
            get {
                return ResourceManager.GetString("XAML_Path", resourceCulture);
            }
        }
        
        public static string XAML_Reinstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Reinstall_Mod", resourceCulture);
            }
        }
        
        public static string XAML_Mod_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Mod_SearchBar", resourceCulture);
            }
        }
        
        public static string XAML_Setting_DisableDependency_Delete {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Delete", resourceCulture);
            }
        }
        
        public static string XAML_Setting_DisableDependency_Disable {
            get {
                return ResourceManager.GetString("XAML_Setting_DisableDependency_Disable", resourceCulture);
            }
        }
        
        public static string XAML_Setting_EnableDependency_Enable {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Enable", resourceCulture);
            }
        }
        
        public static string XAML_Setting_EnableDependency_Install {
            get {
                return ResourceManager.GetString("XAML_Setting_EnableDependency_Install", resourceCulture);
            }
        }
        
        public static string XAML_TroubleShoot {
            get {
                return ResourceManager.GetString("XAML_TroubleShoot", resourceCulture);
            }
        }
        
        public static string XAML_Uninstall_MelonLoader {
            get {
                return ResourceManager.GetString("XAML_Uninstall_MelonLoader", resourceCulture);
            }
        }
        
        public static string XAML_Uninstall_Mod {
            get {
                return ResourceManager.GetString("XAML_Uninstall_Mod", resourceCulture);
            }
        }
        
        public static string XAML_Update_Mod {
            get {
                return ResourceManager.GetString("XAML_Update_Mod", resourceCulture);
            }
        }
        
        public static string XAML_DownloadSource_Custom {
            get {
                return ResourceManager.GetString("XAML_DownloadSource_Custom", resourceCulture);
            }
        }
        
        public static string XAML_UseCustomDownloadSource {
            get {
                return ResourceManager.GetString("XAML_UseCustomDownloadSource", resourceCulture);
            }
        }
        
        public static string XAML_CustomDownloadSourceFormat {
            get {
                return ResourceManager.GetString("XAML_CustomDownloadSourceFormat", resourceCulture);
            }
        }
        
        public static string XAML_Chart_SearchBar {
            get {
                return ResourceManager.GetString("XAML_Chart_SearchBar", resourceCulture);
            }
        }
        
        public static string XAML_Download_Chart {
            get {
                return ResourceManager.GetString("XAML_Download_Chart", resourceCulture);
            }
        }
        
        public static string XAML_Chart_Downloads {
            get {
                return ResourceManager.GetString("XAML_Chart_Downloads", resourceCulture);
            }
        }
        
        public static string XAML_Chart_Likes {
            get {
                return ResourceManager.GetString("XAML_Chart_Likes", resourceCulture);
            }
        }
        
        public static string XAML_Charter {
            get {
                return ResourceManager.GetString("XAML_Charter", resourceCulture);
            }
        }
        
        public static string XAML_CustomAlbumsFolder {
            get {
                return ResourceManager.GetString("XAML_CustomAlbumsFolder", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOptions {
            get {
                return ResourceManager.GetString("XAML_ChartSortOptions", resourceCulture);
            }
        }
        
        public static string XAML_ChartFilterTypes {
            get {
                return ResourceManager.GetString("XAML_ChartFilterTypes", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Default {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Default", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Likes {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Likes", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Downloads {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Downloads", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Latest {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Latest", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Name {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Name", resourceCulture);
            }
        }
        
        public static string XAML_ChartSortOption_Level {
            get {
                return ResourceManager.GetString("XAML_ChartSortOption_Level", resourceCulture);
            }
        }
        
        public static string XAML_ChartFilterType_Easy {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Easy", resourceCulture);
            }
        }
        
        public static string XAML_ChartFilterType_Hard {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hard", resourceCulture);
            }
        }
        
        public static string XAML_ChartFilterType_Master {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Master", resourceCulture);
            }
        }
        
        public static string XAML_ChartFilterType_Hidden {
            get {
                return ResourceManager.GetString("XAML_ChartFilterType_Hidden", resourceCulture);
            }
        }
        
        public static string XAML_SearchBar {
            get {
                return ResourceManager.GetString("XAML_SearchBar", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_ChartName {
            get {
                return ResourceManager.GetString("XAML_InfoJson_ChartName", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_Author {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Author", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_LevelDesigner {
            get {
                return ResourceManager.GetString("XAML_InfoJson_LevelDesigner", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_Scene {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Scene", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_BPM {
            get {
                return ResourceManager.GetString("XAML_InfoJson_BPM", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_Difficulty {
            get {
                return ResourceManager.GetString("XAML_InfoJson_Difficulty", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_SearchTags {
            get {
                return ResourceManager.GetString("XAML_InfoJson_SearchTags", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_HideBmsMode {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsMode", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_HideBmsDifficulty {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsDifficulty", resourceCulture);
            }
        }
        
        public static string XAML_InfoJson_HideBmsMessage {
            get {
                return ResourceManager.GetString("XAML_InfoJson_HideBmsMessage", resourceCulture);
            }
        }
        
        public static string XAML_ChooseChartPath {
            get {
                return ResourceManager.GetString("XAML_ChooseChartPath", resourceCulture);
            }
        }
        
        public static string XAML_Scene_SpaceStation {
            get {
                return ResourceManager.GetString("XAML_Scene_SpaceStation", resourceCulture);
            }
        }
        
        public static string XAML_Scene_Retrocity {
            get {
                return ResourceManager.GetString("XAML_Scene_Retrocity", resourceCulture);
            }
        }
        
        public static string XAML_Scene_Castle {
            get {
                return ResourceManager.GetString("XAML_Scene_Castle", resourceCulture);
            }
        }
        
        public static string XAML_Scene_RainyNight {
            get {
                return ResourceManager.GetString("XAML_Scene_RainyNight", resourceCulture);
            }
        }
        
        public static string XAML_Scene_Candyland {
            get {
                return ResourceManager.GetString("XAML_Scene_Candyland", resourceCulture);
            }
        }
        
        public static string XAML_Scene_Oriental {
            get {
                return ResourceManager.GetString("XAML_Scene_Oriental", resourceCulture);
            }
        }
        
        public static string XAML_Scene_LetsGroove {
            get {
                return ResourceManager.GetString("XAML_Scene_LetsGroove", resourceCulture);
            }
        }
        
        public static string XAML_Scene_Touhou {
            get {
                return ResourceManager.GetString("XAML_Scene_Touhou", resourceCulture);
            }
        }
        
        public static string XAML_Scene_DJMAX {
            get {
                return ResourceManager.GetString("XAML_Scene_DJMAX", resourceCulture);
            }
        }
        
        public static string XAML_ConfigFile {
            get {
                return ResourceManager.GetString("XAML_ConfigFile", resourceCulture);
            }
        }
        
        public static string XAML_LaunchVanilla {
            get {
                return ResourceManager.GetString("XAML_LaunchVanilla", resourceCulture);
            }
        }
        
        public static string XAML_LaunchModded {
            get {
                return ResourceManager.GetString("XAML_LaunchModded", resourceCulture);
            }
        }
        
        public static string XAML_Back {
            get {
                return ResourceManager.GetString("XAML_Back", resourceCulture);
            }
        }
        
        public static string XAML_News {
            get {
                return ResourceManager.GetString("XAML_News", resourceCulture);
            }
        }
        
        public static string XAML_Page_ModManage {
            get {
                return ResourceManager.GetString("XAML_Page_ModManage", resourceCulture);
            }
        }
        
        public static string XAML_Page_About {
            get {
                return ResourceManager.GetString("XAML_Page_About", resourceCulture);
            }
        }
        
        public static string XAML_Page_ChartManage {
            get {
                return ResourceManager.GetString("XAML_Page_ChartManage", resourceCulture);
            }
        }
        
        public static string XAML_Page_ChartToolkit {
            get {
                return ResourceManager.GetString("XAML_Page_ChartToolkit", resourceCulture);
            }
        }
        
        public static string XAML_Page_Home {
            get {
                return ResourceManager.GetString("XAML_Page_Home", resourceCulture);
            }
        }
        
        public static string XAML_Page_ModDevelop {
            get {
                return ResourceManager.GetString("XAML_Page_ModDevelop", resourceCulture);
            }
        }
        
        public static string XAML_Page_Setting {
            get {
                return ResourceManager.GetString("XAML_Page_Setting", resourceCulture);
            }
        }
        
        public static string XAML_Page_LogAnalysis {
            get {
                return ResourceManager.GetString("XAML_Page_LogAnalysis", resourceCulture);
            }
        }
        
        public static string XAML_Page_Category_Modding {
            get {
                return ResourceManager.GetString("XAML_Page_Category_Modding", resourceCulture);
            }
        }
        
        public static string XAML_Page_Category_Charting {
            get {
                return ResourceManager.GetString("XAML_Page_Category_Charting", resourceCulture);
            }
        }
    }
}
