namespace MuseDashModTools.Generators;

internal static class SourceGenerationTexts
{
    internal const string Header = """
                                   //------------------------------------------------------------------------------
                                   // <auto-generated>
                                   //     This code was generated by the MuseDashModTools source generator
                                   //
                                   //     Changes to this file may cause incorrect behavior and will be lost if
                                   //     the code is regenerated.
                                   // </auto-generated>
                                   //------------------------------------------------------------------------------

                                   #nullable enable


                                   """;

    internal static string GetGeneratedCodeAttribute(string generatorName) =>
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("MuseDashModTools.SourceGenerators.{generatorName}", "{SourceGeneratorVersion}")]""";
}