name: Build Project

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'dev/rewrite'
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'dev/rewrite'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release
        target-platform:
          - { os: ubuntu-latest, name: linux }
          - { os: windows-latest, name: win }
          - { os: macos-latest, name: osx }
        target-arch:
          - x64
          - arm64
        dotnet-version:
          - '8.0'
        self-contained:
          - true
          - false
    runs-on: ${{ matrix.target-platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Project
        run: |
          dotnet publish --configuration=${{ matrix.build-type }} --arch=${{ matrix.target-arch }} --self-contained=${{ matrix.self-contained }}

      - name: Test Project
        run: |
          dotnet test --configuration=${{ matrix.build-type }}

      - name: List Result
        working-directory: ./
        run: |
          ls -l bin/${{ matrix.build-type }}/net${{ matrix.dotnet-version }}/${{matrix.target-platform.name}}-${{ matrix.target-arch }}/publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MuseDashModTools-${{ matrix.build-type }}-${{matrix.target-platform.name}}-net${{ matrix.dotnet-version }}-${{ matrix.target-arch }}-${{ matrix.self-contained && 'self-contained' || 'runtime-required' }}
          path: bin/${{ matrix.build-type }}/net${{ matrix.dotnet-version }}/${{matrix.target-platform.name}}-${{ matrix.target-arch }}/publish/*
