name: Build and Test Project

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'assets/**'
      - 'CHANGELOG.md'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    branches:
      - 'master'
      - 'dev'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target-platform:
          - { os: ubuntu-latest, name: linux }
          - { os: windows-latest, name: win }
        target-arch:
          - x64
          # - arm64
        dotnet-version:
          - '9.0'

    runs-on: ${{ matrix.target-platform.os }}
    env:
      AvAccelerateKey: ${{ secrets.AVACCELERATEKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Project
        run: |
          dotnet publish

      - name: Test Project
        run: |
          dotnet test -c Release --no-build

      - name: List Output Directory
        run: |
          ls -la bin/Output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MuseDashModTools-${{matrix.target-platform.name}}-${{ matrix.target-arch }}
          path: bin/Output/*
